name: Build

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: -Dsonar.projectBaseDir=.
          SONAR_TOKEN: 'squ_da7a61b39943f4d8b0cb09458ba20362ed06f8c4'
          SONAR_HOST_URL: 'https://sq.accuknox.com'
          SONAR_SCANNER_EXTRA_ARGS: >
            -Dsonar.exclusions=**/*.java
